### ISSUE TITLE
[BUG] Empty news feed upon start up

### ISSUE THREAD

**Issue by casualsailo** [eni9889/FB-PP-Issues#1]
iOS Version: 9.3.3
Facebook Version: 85.0
FB++: Tweak version, v1.6r-11

Main Feed Type: Most Recent Feed

I just installed and purchased a license for FB++ today

Initially, the facebook app started up just fine with the news feed page loading the stories. After a respring, I noticed that everytime that the facebook app started up, a "No stories to show" message would pop up

Clicking the "Retry" button 1-3 times loads the stories most of the time. But very rarely, no matter how many times I click the "Retry" button, it would not load the stories. Leading me to have to respring and try again.

<img width="375" alt="img_2555" src="https://cloud.githubusercontent.com/assets/16842318/24327120/87d6a412-117d-11e7-9cab-79b74966361c.png">

**Comment by eni9889** [comment]
@darrickteng this is an issue with FB itself I believe
