### ISSUE TITLE
No settings on Facebook++

### ISSUE THREAD

**Issue by WCHighfill** [eni9889/FB-PP-Issues#3]
Since the past couple Facebook++ updates I have not been able to find the settings. I know they are in the Facebook app, but they are no longer there.

iOS
9.3.2

Facebook Version
86.0

FB++ Version
1.6r16

**Comment by TheNightRider12** [comment]
Click on the 3 lines at the bottom right at the main screen. And the settings buttons should be at the bottom [image](https://imgur.com/a/oGMmH)

**Comment by WCHighfill** [comment]
https://imgur.com/gallery/MrXr3

**Comment by casualsailo** [comment]
Have you tried uninstalling facebook and reinstalling it?

I've tried facebook v82 all the way to v87 and I see the "FB ++ / Settings" button

**Comment by TheNightRider12** [comment]
make sure there also aren't any conflicting tweaks that have to do with Facebook. As that can potentially mess things up.

**Comment by eni9889** [comment]
@WCHighfill this should be fixed in the latest version
