### ISSUE TITLE
[Bug]? I think. FB++ Settings button showing up twice

### ISSUE THREAD

**Issue by TheNightRider12** [eni9889/FB-PP-Issues#5]
iOS: 10.1.1
Type: Jailbreak
Phone Model: iPhone6S
Facebook Version: 87.0
Tweak: 1.6r-20

Facebook++ Settings button/option is showing up twice. On the top [Shown Here](https://puu.sh/vbK6y/21886ef594.jpg)
And on the bottom [Shown here](https://puu.sh/vbK9u/b61deb1158.PNG)

**Comment by eni9889** [comment]
Yep this is on purpose in case Facebook changes something in the future
